POST http://localhost:3003/api/blogs

Content-Type: application/json

{
    "title": "Titulo del blog",
    "author": "Pedro Pica",
    "url": "https://fullstackopen-part3-m1h6.onrender.com/",
    "likes": 19
}

###
GET http://localhost:3003/api/blogs
